#ifndef FUSECPP_COMMON_HPP
#define FUSECPP_COMMON_HPP

#if defined(FUSECPP_BAD_CAST_THROW_EXCEPTION)
#endif

#if defined(FUSECPP_BAD_CAST_THROW_EXCEPTION_IN_SEARCH)
#endif


#endif  // FUSECPP_COMMON_HPP
